//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazi.Sube2.CollectionsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciler
    {
        public int OgrenciId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int Numara { get; set; }
        public int SinifId { get; set; }
    
        //Navigation Property
        public tblSiniflar tblSiniflar { get; set; }
    }
}
